# Generated by Django 4.0.4 on 2022-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
