# Generated by Django 4.0.4 on 2022-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0005_history_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Polity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(upload_to='media')),
            ],
        ),
    ]
