# Generated by Django 4.0.4 on 2022-06-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0006_biology_chemistry_geography_physics_polity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_actual_price', models.IntegerField()),
                ('history_discount_price', models.IntegerField()),
                ('physics_actual_price', models.IntegerField()),
                ('physics_discount_price', models.IntegerField()),
                ('chemistry_actual_price', models.IntegerField()),
                ('chemistry_dicount_price', models.IntegerField()),
                ('biology_actual_price', models.IntegerField()),
                ('biology_discount_price', models.IntegerField()),
                ('polity_actual_price', models.IntegerField()),
                ('polity_discount_price', models.IntegerField()),
                ('geography_actual_price', models.IntegerField()),
                ('geography_discount_price', models.IntegerField()),
            ],
        ),
    ]
