# Generated by Django 4.0.4 on 2022-06-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0008_alter_notes_price_biology_actual_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectby_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('actual_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('home_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesapp.home_notes')),
            ],
        ),
        migrations.DeleteModel(
            name='Biology',
        ),
        migrations.DeleteModel(
            name='Chemistry',
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Notes_price',
        ),
        migrations.DeleteModel(
            name='Physics',
        ),
        migrations.DeleteModel(
            name='Polity',
        ),
    ]
