# Generated by Django 4.0.4 on 2022-06-08 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0009_subjectby_notes_delete_biology_delete_chemistry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('subjectby_notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notesapp.subjectby_notes')),
            ],
        ),
    ]
