# Generated by Django 4.0.4 on 2022-06-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0010_payments_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments_details',
            name='subjectby_notes',
        ),
    ]
