# Generated by Django 4.0.4 on 2022-06-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0011_remove_payments_details_subjectby_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
