# Generated by Django 4.0.4 on 2022-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0013_download_pdf_subjectby_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_pdf',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
