# Generated by Django 4.0.4 on 2022-06-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0016_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emial',
            new_name='email',
        ),
    ]
