# Generated by Django 4.0.4 on 2022-06-15 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notesapp', '0018_download_pdf_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download_pdf',
            options={'verbose_name': 'upload_notes'},
        ),
        migrations.AddField(
            model_name='download_pdf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
